FROM node:22

# Set working directory
WORKDIR /app

# Copy and install dependencies
COPY backend/package*.json ./
RUN npm install

# Copy the rest of the files
COPY backend/ .

# Expose backend port
EXPOSE 3000

# Start the NestJS app
CMD ["npm", "run", "start:prod"]