services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "7777:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge