version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    ports:
      - "777:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
